pf_r2000:
  ros__parameters:
    transport: "udp"
    scanner_ip: "10.0.10.9"
    # port: 3000 # optional
    device: "R2000"
    start_angle: -1800000
    max_num_points_scan: 0
    packet_type: "C"
    scan_topic: "/pf/scan"
    frame_id: "scanner_link"
    watchdogtimeout: 60000
    watchdog: true
    pfsdp_init: ['scan_frequency=10', 'samples_per_scan=25200', 'filter_type=maximum', 'filter_width=8', 'filter_error_handling=tolerant', 'filter_maximum_margin=100', 'lcm_detection_sensitivity=medium', 'lcm_detection_period=5000', 'lcm_sector_enable=on,on,on,on,on,on,on,on,on,on,on,on', 'hmi_application_text_1=R2000_UHD_HarshEnvironment', 'hmi_display_mode=application_text']
