pf_r2400:
  ros__parameters:
    transport: "udp"
    scanner_ip: "10.0.0.62"
    # port: 3000 # optional
    device: "R2400"
    start_angle: -1800000
    max_num_points_scan: 0
    packet_type: "C"
    scan_topic: "/pf/scan"
    frame_id: "scanner_link"
    watchdogtimeout: 60000
    watchdog: false
    pfsdp_init: ['scan_frequency=20', 'samples_per_scan=3600', 'scan_preprocessing=on']
