string name         # name of the parameter, e.g. scan_frequency
---
string value        # value of the parameter as string, e.g. "10.5"
int32 error_code    # 0 if everything went well in the sensor
string error_text   # verbose explanation of error_code value


