---
string protocol_name # pfsdp
int32 version_major # e.g. 1
int32 version_minor # e.g. 5
string[] commands   # list of all PFSDP commands supported by the sensor
int32 error_code    # 0 if everything went well in the sensor, <0 network/http error, >0 pfsdp error
string error_text   # verbose explanation of error_code value


